version: "3.3"
services:
  mongodb:
    container_name: guaca_mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
      MONGO_INITDB_DATABASE: "admindb"
    # we are using only binding (a file) since we dont need consistent data.
    # Data will be lost if container is deleted
    volumes:
    - ./mongodb/setup.js:/docker-entrypoint-initdb.d/setup.js:ro
    ports:
      - "27017:27017"
  mongoexpress:
    container_name: guaca_mongoexpress
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: "guaca_mongodb"
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_USERNAME: "admin"
      ME_CONFIG_MONGODB_AUTH_PASSWORD: "admin"
    depends_on:
      - mongodb
    ports:
      - "8888:8081"
  backend:
    container_name: guaca_nodejs
    build:
      context: ./nodejs
      dockerfile: nodejs.Dockerfile
    # we will not be using this until we need consistent data
    #volumes:
    #  - .:/usr/app/
    #  - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
